# Generated by Django 4.2.12 on 2025-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("token", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("airesponse", models.JSONField()),
                ("roomid", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingTranscription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("speaker", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("roomid", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("order_no", models.IntegerField()),
            ],
        ),
    ]
