# Generated by Django 4.2.12 on 2025-03-03 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FutureMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("duration_minutes", models.IntegerField()),
                (
                    "participants",
                    models.TextField(help_text="Comma-separated emails or names"),
                ),
                ("agenda", models.TextField(blank=True, null=True)),
                ("trello_task_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
