# Generated by Django 4.2.12 on 2025-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0001_initial"),
    ]

    operations = []
