# Generated by Django 4.2.12 on 2025-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtranscription",
            name="createdat",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="meetingtranscription",
            name="updatedat",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
