# Generated by Django 4.2.12 on 2025-03-03 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futuremeeting",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="futuremeeting",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
