# Generated by Django 5.1.6 on 2025-02-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTranscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speaker', models.CharField(max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.meeting')),
            ],
        ),
    ]
