# Generated by Django 4.2.12 on 2025-02-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0002_auto_20250228_1524"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("roomid", models.CharField(max_length=255)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
