# Generated by Django 4.2.12 on 2025-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0002_alter_meetingtranscription_createdat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtranscription",
            name="createdat",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
