# Generated by Django 4.2.12 on 2025-03-03 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0002_customuser_meeting_meetingtranscription_meetinguser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futuremeeting",
            name="date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="futuremeeting",
            name="time",
            field=models.TextField(blank=True, null=True),
        ),
    ]
