# Generated by Django 5.1.6 on 2025-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_meeting_meetingtranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranscription',
            name='text',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
