# Generated by Django 4.2.12 on 2025-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0003_alter_meetingtranscription_createdat"),
    ]

    operations = [
        migrations.RemoveField(model_name="meeting", name="updatedat",),
        migrations.RemoveField(model_name="meetingtranscription", name="updatedat",),
        migrations.RemoveField(model_name="meetinguser", name="updatedat",),
        migrations.AlterField(
            model_name="meeting", name="airesponse", field=models.JSONField(null=True),
        ),
    ]
