# Generated by Django 5.1.6 on 2025-02-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_meetingtranscription_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtranscription',
            name='text',
            field=models.TextField(),
        ),
    ]
