# Generated by Django 4.2.12 on 2025-03-03 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0004_remove_meeting_updatedat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="updatedat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
